<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Vastator Oficial</title>
<link href="/css/bootstrap.css" rel="stylesheet">

<script src="/js/jquery.min.js" language="javascript"></script>
<script src="/js/modernizr.min.js" language="javascript"></script>
<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea"
 });
</script>
<link rel="icon"  type="image/png" href="/favicon.ico">
</head>
<body>
<div class="container">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/">Vastator</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="">
              <a href="./index.html">Home</a>
            </li>
            <li class="">
              <a href="/admin/news">Noticias</a>
            </li>
            <li class="">
              <a href="/admin/tour">Tour</a>
            </li>
            <li class="">
              <a href="/admin/galeria">Galeria</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <br />
  <br />
  <br />
  <br />
  <?php echo $this->layout()->content; ?>
</div>

</body>
</html>
