<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Vastator Oficial</title>
<link href="/css/bootstrap.css" rel="stylesheet">
<link rel="stylesheet" href="/js/jquery-ui-1.10.3/themes/base/jquery.ui.all.css">
  
<script src="/js/jquery.min.js" language="javascript"></script>
<script src="/js/modernizr.min.js" language="javascript"></script>
<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
<script src="/js/jquery-ui-1.10.3/ui/jquery.ui.core.js"></script>
<script src="/js/jquery-ui-1.10.3/ui/jquery.ui.widget.js"></script>
<script src="/js/jquery-ui-1.10.3/ui/jquery.ui.datepicker.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea"
 });
</script>
<link rel="icon"  type="image/png" href="/favicon.ico">
</head>
<body>
<div class="container">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/" target="_blank">Vastator</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="">
              <a href="/admin/">Slider del Home</a>
            </li>
            <li class="">
              <a href="/admin/videos">Videos del Home</a>
            </li>
            <li class="">
              <a href="/admin/news">Noticias</a>
            </li>
            <li class="">
              <a href="/admin/tour">Tour</a>
            </li>
            <li class="">
              <a href="/admin/gallery">Galeria</a>
            </li>
            <li class="">
              <a href="/admin/the-band">La Banda</a>
            </li>
            <li class="">
              <a href="/admin/logout">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <br />
  <br />
  <br />
  <br />
  <?php if (isset($this->messages) && count($this->messages)):?>
    <div class="alert alert-<?php echo $this->messagesType ? $this->messagesType : 'success'; ?>">
      <?php foreach($this->messages as $message): ?>
        <?php echo $message; ?><br />
      <?php endforeach;?>
    </div>
  <?php endif; ?>
  <?php echo $this->layout()->content; ?>
</div>

</body>
</html>
