<header id="header" class="row">
  <div class="span8">
    <figure id="logo"></figure>
    <nav>
      <a href="/" class="<?php echo $this->selected == 'index'? 'selected':''; ?>" title="Home">Inicio</a>
      <a href="/news" class="<?php echo $this->selected == 'news'? 'selected':''; ?>" title="News">Noticias</a>
      <a href="/tour" class="<?php echo $this->selected == 'tour'? 'selected':''; ?>" title="Tour dates and clinics">Tour</a>
      <a href="/gallery" class="<?php echo $this->selected == 'gallery'? 'selected':''; ?>" title="Images and Videos">Galeria</a>
      <a href="/discography" class="<?php echo $this->selected == 'discography'? 'selected':''; ?>" title="Discography">Discografia</a>
      <!--     <a href="/media" class="<?php echo $this->selected == 'media'? 'selected':''; ?>" title="Media">Media</a> -->
      <a href="/the-band" class="<?php echo $this->selected == 'the-band'? 'selected':''; ?>" title="The Band">La banda</a>
    </nav>
  </div>
  <div class="span4 social">
    <img src="/img/social-icons.png" class="map" id="social-links" usemap="#social-links" border="0" width="471" height="77" alt=""/>
  </div>
  <map id="_social-links" name="social-links">
    <area shape="rect" coords="4,4,45,72" href="http://www.facebook.com/Vastator" target="_blank" alt="Siguenos en Facebook" title="Siguenos en Facebook" />
    <area shape="rect" coords="110,4,70,72" href="https://twitter.com/vastatorband" target="_blank" alt="Siguenos en Twitter" title="Siguenos en Twitter" />
    <area shape="rect" coords="135,4,175,72" href="http://www.instagram.com/vastatoronline" target="_blank" alt="Siguenos en Instagram" title="Siguenos en Instagram" />
    <area shape="rect" coords="200,4,238,72" href="http://www.youtube.com/vastatoronline" target="_blank" alt="Siguenos en Youtube" title="Siguenos en Youtube" />
    <area shape="rect" coords="263,4,324,72" href="#" alt="Siguenos en SoundCloud" target="_blank" title="Siguenos en SoundCloud" />
  </map>
</header>
