<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Vastator Oficial</title>
<link href="/css/bootstrap.css" rel="stylesheet">
<link href="/css/styles.css" rel="stylesheet">

<meta property="fb:app_id" content="261587403990087">
<meta property="og:site_name" content="Vastator">
<meta property="og:title" content="Vastator">
<meta property="og:url" content="http://www.vastator.cl">
<meta property="og:description" content="Vastator Oficial - Heroes del metal latinoamericano">
<meta property="og:image" content="http://www.vastator.cl/img/background.jpg">
<script src="/js/jquery.min.js" language="javascript"></script>
<script src="/js/modernizr.min.js" language="javascript"></script>

<!-- Nivo Slider -->
<link rel="stylesheet" href="/js/nivo-slider/themes/default/default.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/js/nivo-slider/themes/light/light.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/js/nivo-slider/themes/dark/dark.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/js/nivo-slider/themes/bar/bar.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/js/nivo-slider/nivo-slider.css" type="text/css" media="screen" />
<script type="text/javascript" src="/js/nivo-slider/jquery.nivo.slider.js"></script>
<!-- Nivo Slider End -->

<link rel="icon"  type="image/png" href="/favicon.ico">
</head>
<body>
<div class="container">
  <?php echo $this->render('header.phtml'); ?>
  <?php echo $this->layout()->content; ?>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46102421-1', 'vastator.cl');
  ga('send', 'pageview');

</script>
<?php echo $this->inlineScript(); ?>
</body>
</html>
