<h2>Latest News</h2>
<div class="row">
  <div class="span6 news">
    <h3> News Title</h3>
    <p>Published:<br />Oct 10, 2013</p>
    <p><img src="/img/gallery/vast1.jpg" style="float: left"/>Robinsons Brewery today announced that over ONE MILLION pints of TROOPER have been shipped around the world,
    taking total sales to a whopping TWO MILLION pints to date!</p>
    <p class="more"><a href="#">[ More ]</a></p>
  </div>
  <div class="span6 news">
    <h3> News Title</h3>
    <p>Published:<br />Oct 10, 2013</p>
    <p><img src="/img/gallery/vast1.jpg" style="float: left"/>Robinsons Brewery today announced that over ONE MILLION pints of TROOPER have been shipped around the world,
    taking total sales to a whopping TWO MILLION pints to date!</p>
  </div>
  <div class="span6 news">
    <h3> News Title</h3>
    <p>Published:<br />Oct 10, 2013</p>
    <p>Robinsons Brewery today announced that over ONE MILLION pints of TROOPER have been shipped around the world,
    taking total sales to a whopping TWO MILLION pints to date!</p>
  </div>
</div>
