<div class="row">
  <div class="span6 news">
    <h3>Machine Hell</h3>
    <p><img src="/img/gallery/vast1.jpg" style="float: left"/>Robinsons Brewery today announced that over ONE MILLION pints of TROOPER have been shipped around the world,
    taking total sales to a whopping TWO MILLION pints to date!</p>
  </div>
  <div class="span6 news">
    <h3>Hell Only Knows</h3>
    <p><img src="/img/gallery/vast1.jpg" style="float: left"/>Robinsons Brewery today announced that over ONE MILLION pints of TROOPER have been shipped around the world,
    taking total sales to a whopping TWO MILLION pints to date!</p>
  </div>
</div>
