<div class="row">
  <div class="span12">
    <h3>Albums de estudio</h3>
  </div>
  <div class="span6 news">
    <h3>Acoustic Sessions - 2012</h3>
    <img src="/img/discography/acustic.jpg" />
    <p>Acoustic Sessions</p>
  </div>
  <div class="span6 news">
    <h3>Machine Hell - 2010</h3>
    <img src="/img/discography/mh.jpg" />
    <p>Machine Hell</p>
  </div>
  <div class="span6 news">
    <h3>Hell Only Knows - 2007</h3>
    <img src="/img/discography/hok.jpg" />
    <p>Hell Only Knows</p>
  </div>
  <div class="span6 news">
    <h3>Hell Only Knows Deluxe Edition - 2007</h3>
    <img src="/img/discography/hokdeluxe.jpg" />
    <p>Hell Only Knows Deluxe Edition</p>
  </div>
  <div class="span6 news">
    <h3>The Night Of San Juan - 2001</h3>
    <img src="/img/discography/night_of_san_juan.jpg" />
    <p>The Night Of San Juan</p>
  </div>
  <div class="span6 news">
    <h3>Gu&iacute;a Para Odiar A Tu Pr&oacute;jimo - 1999</h3>
    <img src="/img/discography/guia.jpg" />
    <p>Gu&iacute;a Para Odiar A Tu Pr&oacute;jimo</p>
  </div>
  <div class="span12">
    <h3>Demos</h3>
  </div>
  <div class="span6 news">
    <h3>Máxima Entropía - 1989</h3>
    <img src="/img/discography/maxima.jpg" />
    <p>Máxima Entropía</p>
  </div>
  <div class="span6 news">
    <h3>Inconciencia Asesina - 1988</h3>
    <img src="/img/discography/inconciencia.jpg" />
    <p>Inconciencia Asesina</p>
  </div>
  <div class="span6 news" style="clear: both">
    <h3>El Profanador - 1987</h3>
    <img src="/img/discography/profanador.jpg" />
    <p>El Profanador</p>
  </div>
</div>
