<div class="row">
  <div class="span6 news">
    <h3>Machine Hell</h3>
    <p><img src="/img/discography/mh.jpg" style="float: left"/>Machine Hell</p>
  </div>
  <div class="span6 news">
    <h3>Hell Only Knows</h3>
    <p><img src="/img/discography/hok.jpg" style="float: left"/>Hell Only Knows</p>
  </div>
  <div class="span6 news">
    <h3>The Night Of San Juan</h3>
    <p><img src="/img/discography/night_of_san_juan.jpg" style="float: left"/>The Night Of San Juan</p>
  </div>
</div>
