<div class="row">
  <div class="span12">
    <select>
      <option>Now</option>
      <option>2000's</option>
      <option>1990's</option>
      <option>1980's</option>
    </select>
  </div>
</div>
<div class="slider-wrapper theme-default">
  <div id="slider" class="nivoSlider">
    <img src="/img/gallery/vast1.jpg" data-thumb="/img/gallery/vast1.jpg" alt="" />
    <img src="/img/gallery/vast2.jpg" data-thumb="/img/gallery/vast2.jpg" alt="" />
    <img src="/img/gallery/vast3.jpg" data-thumb="/img/gallery/vast3.jpg" alt="" />
  </div>
</div>
<script type="text/javascript">
$(window).load(function() {
  $('#slider').nivoSlider();
});
</script>
