<div class="row">
  <div class="span12">
    <select id="changeGallery">
      <option value="-1">Seleccione una galeria</option>
      <?php foreach($this->gallery as $gallery):?>
      <option <?php echo $gallery['id'] == $this->selected? 'selected="selected"':'' ?> value="<?php echo $gallery['id']; ?>"><?php echo $gallery['description']?></option>
      <?php endforeach; ?>
    </select>
  </div>
</div>
<div class="slider-wrapper theme-default">
  <div id="slider" class="nivoSlider">
    <?php foreach($this->images as $image):?>
    <img src="/img/gallery/<?php echo $image['gallery_id']; ?>/<?php echo $image['image']; ?>" data-thumb="/img/gallery/<?php echo $image['gallery_id']; ?>/<?php echo $image['image']; ?>" />
    <?php endforeach; ?>
  </div>
</div>
<script type="text/javascript">
$(function() {
  $('#slider').nivoSlider();
});
$('#changeGallery').on({
    'change': function(e) {
        if ($(this).val() == -1) {
            window.location = '/gallery';
        } else {
            window.location = '/gallery?id=' + $(this).val();
        }
    }
});
</script>
