<div class="slider-wrapper theme-default">
  <div id="slider" class="nivoSlider">
  <?php foreach($this->photos as $photo): ?>
    <img src="/img/slider/<?php echo $photo?>" data-thumb="/img/slider/<?php echo $photo; ?>" alt="" />
  <?php endforeach; ?>
  </div>
</div>
<div class="row">
  <?php foreach($this->videos as $video): ?>
  <div class="span6">
    <iframe width="465" height="349" src="//www.youtube.com/embed/<?php echo $video; ?>" frameborder="0" allowfullscreen></iframe>
  </div>
  <?php endforeach; ?>
</div>
<script type="text/javascript">
$(window).load(function() {
  $('#slider').nivoSlider();
});
</script>
