<?php $video = $this->video; ?>
<?php $latestNews = $this->news; ?>
<div class="row index">
  <h3 class="span12">&Uacute;ltimas noticias:</h3>
  <div class="span8">
    <div class="row">
    <?php foreach($latestNews as $news):?>
      <?php if ($news['image'] != '' && !is_null($news['youtube'])): ?>
        <div class="span8 news_title">
          <h3><?php echo $news['title']; ?></h3>
          <p>Publicado:<br /><?php echo $news['created']; ?></p>
        </div>
        <div class="span4">
          <a href="/img/gallery/<?php echo $news['id']; ?>/resized/<?php echo $news['image']; ?>" class="fancyLink">
            <img src="/img/gallery/<?php echo $news['id']; ?>/resized/<?php echo $news['image']; ?>" />
          </a>
        </div>
      <?php endif; ?>
      <?php if ($news['youtube'] != ''): ?>
      <div class="span8">
        <iframe width="620" height="465" src="//www.youtube.com/embed/<?php echo $news['youtube']; ?>" frameborder="0" allowfullscreen></iframe>
      </div>
      <?php endif; ?>
        <div class="span4">
        <?php echo $news['comment']; ?>
        </div>
    <?php endforeach;?>
    </div>
  </div>
  <div class="span4">
    <?php echo $this->partial('partials/twitter.phtml'); ?>
    <br />
    <br />
    <iframe width="300" height="225" src="//www.youtube.com/embed/<?php echo $video['youtube']; ?>" frameborder="0" allowfullscreen></iframe>
  </div>
</div>
<br />
<br />
<div class="row">
  <div class="slider-wrapper theme-default">
    <div id="slider" class="span12 nivoSlider">
    <?php foreach($this->photos as $photo): ?>
      <?php if (!file_exists(APPLICATION_PATH . "/../img/slider/resized/{$photo}")) continue; ?>
      <img src="/img/slider/resized/<?php echo $photo?>" data-thumb="/img/slider/<?php echo $photo; ?>" alt="" />
    <?php endforeach; ?>
    </div>
  </div>
</div>

<?php
echo $this->inlineScript()->captureStart();
?>
$(function() {
  $('#slider').nivoSlider();
  $(".fancyLink").fancybox({
    openEffect	: 'elastic',
    closeEffect	: 'elastic',
    fitToView: false,
    helpers : {
        title : {
            type : 'inside'
            }
        }
    });
});
<?php
echo $this->inlineScript()->captureEnd();
?>

<!-- Add fancyBox main JS and CSS files -->
<script type="text/javascript" src="/js/fancybox/source/jquery.fancybox.js?v=2.1.5"></script>
<link rel="stylesheet" type="text/css" href="/js/fancybox/source/jquery.fancybox.css?v=2.1.5" media="screen" />
<!-- Add Button helper (this is optional) -->
<link rel="stylesheet" type="text/css" href="/js/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" />
<script type="text/javascript" src="/js/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
<!-- Add Thumbnail helper (this is optional) -->
<link rel="stylesheet" type="text/css" href="/js/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" />
<script type="text/javascript" src="/js/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
