<div class="row">
  <?php foreach($this->news as $news):?>
  <div class="span9 news">
    <h3><?php echo $news['title']; ?></h3>
    <p>Publicado:<br /><?php echo $news['created']; ?></p>
    <?php if ($news['image'] != '' && !is_null($news['youtube'])): ?>
    <img src="/img/gallery/<?php echo $news['id']; ?>/<?php echo $news['image']; ?>" />
    <?php endif; ?>
    <?php if ($news['youtube'] != ''): ?>
    <iframe width="700" height="525" src="//www.youtube.com/embed/<?php echo $news['youtube']; ?>" frameborder="0" allowfullscreen></iframe>
    <?php endif; ?>
    <?php echo $news['comment']; ?>
  </div>
  <?php endforeach; ?>
<!--
  <div class="span6 news">
    <h3> News Title</h3>
    <p>Published:<br />Oct 10, 2013</p>
    <p><img src="/img/gallery/vast1.jpg" style="float: left"/>Robinsons Brewery today announced that over ONE MILLION pints of TROOPER have been shipped around the world,
    taking total sales to a whopping TWO MILLION pints to date!</p>
    <p class="more"><a href="/index/detail">[ More ]</a></p>
  </div>
  <div class="span6 news">
    <h3> News Title</h3>
    <p>Published:<br />Oct 10, 2013</p>
    <p><img src="/img/gallery/vast1.jpg" style="float: left"/>Robinsons Brewery today announced that over ONE MILLION pints of TROOPER have been shipped around the world,
    taking total sales to a whopping TWO MILLION pints to date!</p>
    <p class="more"><a href="/index/detail">[ More ]</a></p>
  </div>
-->
</div>
