<div class="row">
  <div class="span9 news">
    <h3>Nueva web, nuevas presentaciones, nuevos discos</h3>
    <p>Publicado:<br />Noviembre 15 de 2013</p>
    <p><img src="/img/gallery/vast1.jpg" style="float: left"/>
    Estamos estrenando nueva web. Preparando los temas de lo que sera nuestro nueva producción. Asi como tambien la
    grabación de una presentación en vivo programada para el 4 de enero de 2014</p>
  </div>
<!--
  <div class="span6 news">
    <h3> News Title</h3>
    <p>Published:<br />Oct 10, 2013</p>
    <p><img src="/img/gallery/vast1.jpg" style="float: left"/>Robinsons Brewery today announced that over ONE MILLION pints of TROOPER have been shipped around the world,
    taking total sales to a whopping TWO MILLION pints to date!</p>
    <p class="more"><a href="/index/detail">[ More ]</a></p>
  </div>
  <div class="span6 news">
    <h3> News Title</h3>
    <p>Published:<br />Oct 10, 2013</p>
    <p><img src="/img/gallery/vast1.jpg" style="float: left"/>Robinsons Brewery today announced that over ONE MILLION pints of TROOPER have been shipped around the world,
    taking total sales to a whopping TWO MILLION pints to date!</p>
    <p class="more"><a href="/index/detail">[ More ]</a></p>
  </div>
-->
</div>
