<div class="row">
  <div class="span12">
    <div class="the-band">
      <img  src="/img/gallery/vast1.jpg" style="float: left"/>
    </div>
    <h3>VASTATOR Héroes del Metal Latinoaméricano</h3>
    <p>Vastator esta conformado por:</p>
    <ul>
      <li>Sr. Díaz en voces</li>
      <li>Gerardo Barrenechea en batería y percusión</li>
      <li>Peyote Barrera en bajo</li>
      <li>Ricardo Buquet en guitarras</li>
    </ul>
    <p>A mediados de 1986 en Santiago de Chile nace Vastator de la iniciativa de 4 amigos. El debut en público fue el
    mismo año como banda soporte de Massacre.<br />Entonces Vastator estaba conformado por:</p>
    <ul>
      <li>Nelson D’Aldunce en voces (quien luego fuera conocido como Sr. Díaz)</li>
      <li>Sergio Bustamante en guitarra</li>
      <li>Manuel “Paquete” Horamazabal en bajo</li>
      <li>Gerardo Barrenechea en batería</li>
    </ul>
    <p>Entre 1986 y 1989, Vastator lanzó 3 demos que gozaron de gran popularidad en la escena y que rápidamente
    traspasaron las fronteras del país. Vastator marca a fuego la escena con un espectáculo visual junto al aspecto
    musical.</p>
    <ul>
      <li>El Profanador (1987)</li>
      <li>Inconsciencia Asesina (1988)</li>
      <li>Máxima Entropía (1989)</li>
    </ul>
    <p>Importantes hitos pudo marcar la agrupación en sus primeros años de vida:</p>
    <ul>
      <li>Ser considerados por medios masivos de alcance nacional (Diario La Tercera y Radio Carolina) como una de las
      bandas más populares del país. Un gran logro para una banda underground sin medios económicos ni apoyo de medios.</li>
      <li>Ser conocidos por todo el mundo (sin acceso a INTERNET) marcando especial presencia en Perú, México y Francia.</li>
      <li>La Creación de un Fans Club en Polonia.</li>
      <li>Visitar países vecinos.</li>
      <li>Un grupo de seguidores en Chile que se hizo llamar las Hordas Aliadas.</li> 
    </ul>
    <p>En 1989 la banda tuvo un quiebre que se mantuvo durante nueve años (hasta 1998). Entonces, el regreso de Gerardo
    desde España fue una de las piezas claves para tomar la decisión de volver a grabar. Esta vez con calidad profesional,
    algunos de los viejos clásicos de la banda más un par de temas no realizados previamente.</p>
    <p>Esta iniciativa se transformó en el álbum de 1998 “Guía Para Odiar a Tu Prójimo”, que a la larga sería el puntapié
    inicial de un regreso y una nueva imagen que se mantiene hasta hoy. Durante las sesiones de grabación Paquete abandona
    la banda y es reemplazado por Peyote Barrera.</p>
    <p>Ya con Peyote como bajista consolidado, Vastator edita en 2001 “Night Of San Juan” el primer álbum en inglés.
    Esta producción fue acompañada de la salida de otro de los fundadores, el guitarrista Sergio Bustamante. En su
    reemplazo ingresó Francisco Gutiérrez proveniente de la banda Professed.</p>
    <p>American Line de México reedita “Guía Para Odiar a Tu Prójimo” logrando un nuevo nivel de distribución para el
    grupo. Además de llevar a la banda a visitar México por primera vez.</p> 
    <p>Con esta formación en 2007 editan “Hell Only Knows”, albúm que fuera editado en Chile bajo placa Paladín, en México
    bajo sello American Line y en Francia con Inferno Records. Esto junto a la labor de Digmetalworld permitieron consolidar
    a Vastator como banda de culto a nivel mundial.</p>
    <p>Motivos de fuerza mayor obligaron a la partida de Gutiérrez, el mismo fue reemplazado por Felipe Hernández.</p>
    <ul>
      <li>Sr. Díaz en voces</li>
      <li>Felipe Hernández en guitarras</li>
      <li>Peyote Barrera en bajo</li>
      <li>Gerardo Barrenechea en batería y percusión</li>
    </ul>
    <p>En 2010 se edita “Machine Hell”, tal vez el álbum de mayor repercusión internacional hasta la fecha. Nuevamente
    con el apoyo de Inferno Records.</p>
    <p>La ultima alteración en las filas de Vastator se da para abril de 2013, cuando Felipe Hernández abandona la banda
    y es reemplazado por el guitarrista argentino Ricardo Buquet</p>
    <p>Muchos proyectos que llevarán el show de Vastator a lugares no visitados antes y la edición de nuevos y ambiciosos
    proyectos son los siguientes pasos para quienes se han consolidado como “los héroes del metal latinoamericano”.</p>
  </div>
</div>
