<div class="row">
  <div class="span12">
  <?php if (isset($this->band)):?>
    <div class="the-band">
      <img  src="/img/gallery/<?php echo $this->band['image'];?>" />
    </div>
    <?php echo $this->band['history']; ?>
  <?php endif; ?>
    <div class="member">
      <img src="/img/bio/bajo.jpg" />
      <ul>
        <li>Nombre: Peyote Barrera.</li>
        <li>Posición en la banda: Bajo</li>
        <li>Edad: ?</li>
        <li>Album Favorito de Vastator: El último</li>
        <li>Canción Favorita de Vastator: Las Joyas del Cura</li>
        <li>Influencias Musicales: Steve Harris, Pete Way, Diego Arnedo, Lee Rocker, Lemmy Kilmister, etc</li>
        <li>Otras Influencias: Las buenas y malas influencias del Rock’n Roll</li>
        <li>Personaje de Ficción Favorito: Punisher</li>
        <li>Película: A Clockwork Orange</li>
        <li>Hobby: Coleccionista de Calacas</li>
      </ul>
    </div>
    <div class="member">
      <img src="/img/bio/bateria.jpg" />
      <ul>
        <li>Nombre: Gerardo Barrenechea </li>
        <li>Posición en la banda: Baterista</li>
        <li>Edad: Demasiados años </li>
        <li>Album Favorito de Vastator: Demo Máxima Entropía</li>
        <li>Canción Favorita de Vastator: Las Joyas del Cura</li>
        <li>Influencias Musicales: Gene Hoglan, Kim Ruzz, Kliff Bur, Gustav Mahler y Tchaikowsky</li>
        <li>Otras Influencias: Roberto Parra Sandoval, el folclor de atacama</li>
        <li>Personaje de Ficción Favorito: Demonio de Tazmania</li>
        <li>Película: El Quinto Elemento</li>
        <li>Hobby: Ingenieria, Electricidad y Macroeconomía</li>
      </ul>
    </div>
    <div class="member">
      <img src="/img/bio/voz.jpg" />
      <ul>
        <li>Nombre: Sr. Díaz</li>
        <li>Posición en la banda: Cantante</li>
        <li>Edad: Eterno</li>
        <li>Album Favorito de Vastator: Night of San Juan</li>
        <li>Canción Favorita de Vastator: Máxima Entropía</li>
        <li>Influencias Rob Halford, Geoff Tate, Bruce Dickinson, Pavarotti, Tom Jones y Jeff Lynne</li>
        <li>Otras Influencias: Oscar Wilde, Alejandro Dumas, Franz Kafka y Clive Barker</li>
        <li>Personaje de Ficción Favorito: Pinhead</li>
        <li>Película: Omega Man</li>
        <li>Hobby: Actor, Entretenedor y  Diseñador</li>
      </ul>
    </div>
    <div class="member">
      <img src="/img/bio/guitarra.jpg" />
      <ul>
        <li>Nombre: Ricardo "Enkil" Buquet</li>
        <li>Posición en la banda: A la izquierda</li>
        <li>Edad: 34</li>
        <li>Album Favorito de Vastator: Machine Hell</li>
        <li>Canción Favorita de Vastator: Fiend</li>
        <li>Influencias Musicales: Michael Romeo, Chris Impellitteri, Yngwie Malmsteen, Frank Gambale, Paul Gilbert.</li>
        <li>Otras Influencias: Michael Ende, Anne Rice, Bram Stoker</li>
        <li>Personaje de Ficción Favorito: Dracula</li>
        <li>Película: Interview With The Vampire</li>
        <li>Hobby: Programación, Astronomia, Física Cuantica</li>
      </ul>
    </div>
  </div>
</div>
