<div class="row">
  <?php $lastPrintedYear = null; ?>
  <?php foreach($this->tour as $tour): ?>
  <?php
  $year = array_pop(explode('/', $tour['created']));
  if ($year != $lastPrintedYear):
    $lastPrintedYear = $year;
  ?>
  <div class="span12">
    <h3><?php echo $year; ?></h3>
  </div>
  <?php endif; ?>
  <div class="span3">
    <?php echo $tour['created']; ?>
  </div>
  <div class="span9">
    <?php echo $tour['location']; ?>
  </div>
  <?php endforeach; ?>
</div>
