<div class="row">
  <div class="span12">
    <h3>2014</h3>
  </div>
  <div class="span2">
    Sabado 4 de Enero
  </div>
  <div class="span9">
    Grabación disco en vivo
  </div>
  <div class="span12">
    <h3>2013</h3>
  </div>
  <div class="span2">
    Sabado 7 de Diciembre
  </div>
  <div class="span9">
    Maipu
  </div>
  <div class="span2">
    Sunday 3 de Agosto
  </div>
  <div class="span9">
    Recoleta
  </div>
  <div class="span2">
    Sabado 6 de Julio
  </div>
  <div class="span9">
    Oxido Bar
  </div>
</div>
