<div class="row">
  <?php $lastPrintedYear = null; ?>
  <?php foreach($this->tour as $tour): ?>
  <?php
  $year = array_pop(explode('/', $tour['created']));
  if ($year != $lastPrintedYear):
    $lastPrintedYear = $year;
  ?>
  <div class="span12">
    <h3><?php echo $year; ?></h3>
  </div>
  <?php endif; ?>
  <div class="span3">
    <?php echo $tour['created']; ?>
  </div>
  <div class="span9">
    <?php echo $tour['location']; ?>
    <?php if ($tour['gallery_id']): ?>
      <a alt="ver galeria de imagenes" title="ver galeria de imagenes" href="/index/gallery-detail?id=<?php echo $tour['gallery_id']?>"><img src="/img/camera.png" width="20"/></a>
    <?php endif; ?>
  </div>
  <?php endforeach; ?>
</div>
