<header id="header">
  <figure id="logo"></figure>
  <nav>
    <a href="/" title="Home">Home</a>
    <a href="/index/news" title="News">News</a>
    <a href="/index/tour" title="Tour dates and clinics">Tour</a>
    <a href="/index/gallery" title="Images and Videos">Gallery</a>
    <a href="/index/discography" title="Discography and Bootlegs">Discography</a>
    <a href="/index/the-band" title="The Band">The Band</a>
  </nav>
</header>
