<header id="header">
  <figure id="logo"></figure>
  <nav>
    <a href="/" class="<?php echo $this->selected == 'index'? 'selected':''; ?>" title="Home">Home</a>
    <a href="/index/news" class="<?php echo $this->selected == 'news'? 'selected':''; ?>" title="News">News</a>
    <a href="/index/tour" class="<?php echo $this->selected == 'tour'? 'selected':''; ?>" title="Tour dates and clinics">Tour</a>
    <a href="/index/gallery" class="<?php echo $this->selected == 'gallery'? 'selected':''; ?>" title="Images and Videos">Gallery</a>
    <a href="/index/discography" class="<?php echo $this->selected == 'discography'? 'selected':''; ?>" title="Discography and Bootlegs">Discography</a>
    <a href="/index/the-band" class="<?php echo $this->selected == 'the-band'? 'selected':''; ?>" title="The Band">The Band</a>
  </nav>
</header>
