<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Vastator Oficial</title>
<link href="/css/bootstrap.css" rel="stylesheet">
<link href="/css/styles.css" rel="stylesheet">

<meta property="fb:app_id" content="261587403990087">
<meta property="og:site_name" content="Vastator">
<meta property="og:title" content="Vastator">
<meta property="og:url" content="http://www.vastator.cl">
<meta property="og:description" content="Vastator Oficial - Heroes del metal latinoamericano">
<meta property="og:image" content="http://www.vastator.cl/img/background.jpg">
<script src="/js/jquery.min.js" language="javascript"></script>
<script src="/js/modernizr.min.js" language="javascript"></script>

<!-- Nivo Slider -->
<link rel="stylesheet" href="/js/nivo-slider/themes/default/default.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/js/nivo-slider/themes/light/light.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/js/nivo-slider/themes/dark/dark.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/js/nivo-slider/themes/bar/bar.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/js/nivo-slider/nivo-slider.css" type="text/css" media="screen" />
<script type="text/javascript" src="/js/nivo-slider/jquery.nivo.slider.js"></script>
<!-- Nivo Slider End -->

<link rel="icon"  type="image/png" href="/favicon.ico">
</head>
<body>
<div class="container">
  <?php echo $this->partial('header.phtml'); ?>
  <?php echo $this->layout()->content; ?>
</div>

</body>
</html>
